<?php

class ModelsTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		// DB::table('models')->truncate();

		$models = array(
			['name'=>'Lange 1', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Millenary', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Royal Oak', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Royal Oak Off Shore', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Tradition', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Capland', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Classima', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Hampton', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Linea', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'BR01', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'BR02', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'BR03', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Léman', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Fifty Fathoms', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Classique', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Grand Complication', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Marine', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Type XX', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Type XXI', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Tourbillon', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Chronomat', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Colt', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Emergency', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Navitimer', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'SuperOcean', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'B Zero', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Ballon Bleu', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Baignoire', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Calibre', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Must de cartier', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Pasha', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Santos', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Roadster', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Rotonde', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Ronde Louis', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Tank', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'J12', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Happy Sport', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'LUC', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Mille Miglia', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Conqistador', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Arceau', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Cape Cod', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Clipper', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Heure H', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Kelly', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Kelly 2', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Carrera', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Monaco', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Big Bang', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'King Power', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Classic Fusion', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'MP', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Aquatimer', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Da Vinci', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Portofino', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Portugaise', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Amvox', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Duomètre', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Master', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Reverso ', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Squadra', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Octa', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Constellation', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'De Ville', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Seamaster', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Speedmaster', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Luminor', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Radiomir', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Aquanaut', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Calatrava', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Complication', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Ellipse', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Gondolo', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Nautilus', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Twenty Four', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Vintage', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Air King', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Date', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Datejust', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Day-Date', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Daytona', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Explorer', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'GMT Master', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Milgauss', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Oyster', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Perpetual', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Sea-Dweller', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Sky-Dweller', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Submariner', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Yacht-Master', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'Aquaracer', 'created_at'=>new DateTime, 'updated_at' => new DateTime],
			['name'=>'El Primero', 'created_at'=>new DateTime, 'updated_at' => new DateTime]
		);

		// Uncomment the below to run the seeder
		DB::table('models')->insert($models);
	}

}
